### ISSUE TITLE
support openssl 1.1.x?

### ISSUE THREAD

**Issue by youxiaojie** [zinglau/obfuscated-openssh-patches#8]
dear friend,I use this patch http://www.linuxfromscratch.org/blfs/view/8.2/postlfs/openssh.html http://www.linuxfromscratch.org/patches/blfs/8.2/openssh-7.6p1-openssl-1.1.0-1.patch
to compile in openssl 1.1.howerver get the error:
obfuscate.c -o obfuscate.o
obfuscate.c: In function ‘generate_key’:
obfuscate.c:160:13: error: storage size of ‘ctx’ isn’t known
  EVP_MD_CTX ctx;
             ^~~
obfuscate.c:160:13: warning: unused variable ‘ctx’ [-Wunused-variable]
make: *** [Makefile:152: obfuscate.o] Error 1

I think this is because of 1.0.2x openssl, can you fix it?
thanks

**Comment by zinglau** [comment]
Currently the patch does not seem to be compatible with OpenSSL 1.1.* (see also #5).

It appears that upstream is still undecided with regard to how to proceed with this issue, so I personally do not yet intend to invest much efforts into this.

Both Debian and Ubuntu are now shipping with two OpenSSL versions together, so it's still ok for the time being.
